import axios from "axios"

export const employeeLeadsWithFilter = async( setIndividualLeads, employeeAutoGeneratedID = '', coordinatorAutoGeneratedID = '', pageCount=1, limit = 15, startDate='', endDate='' ) => {
    try{
        const sendRequest = await axios.get(`${process.env.REACT_APP_URL}/client/fetchClients/?page=${pageCount}&limit=${limit}&empID=${employeeAutoGeneratedID}&TLID=${coordinatorAutoGeneratedID}&startDate=${startDate}&endDate=${endDate}`);
        const response = await sendRequest.data;
        console.log(response);
        const { success } = response;
        if(success){
            // console.log(response.clients);
            setIndividualLeads !== null && setIndividualLeads(response.clients);
            return response.clients;
        }
    }catch(error){
        console.log(error);
    }
}